### ISSUE TITLE
Add "Out of Office" Message Handling

### ISSUE THREAD

**Issue by ZrowGz** [degen-workgroup/DEGEN#145]
> I think it would be cool to integrate auto replies for members that assign themselves the "out of office" role. This is for when that person gets tagged while they're "out of office." DEGEN could send a DM to the member with the role, notifying them of the tag with a link to the comment or convo. Maybe include a preview of the message? 
> This is just an idea. It doesn't have to be a priority or implemented by a specific date. I just think it would be a really cool feature that would help DEGEN's functionality when it goes to market.
> Example: https://discord.com/channels/834499078434979890/882325552999043132/882736839478349834

Requestor: Ap0ll0517
Scope of implementation: DAO Wide

**Comment by jonvaljonathan** [comment]
I'll will take a run at this one.

**Comment by amaredeus** [comment]
Done in Mad hatter!
