### ISSUE TITLE
POAP Manager Permissions

### ISSUE THREAD

**Issue by ZrowGz** [degen-workgroup/DEGEN#169]
>With more guilds beginning to have elected guild coordinators who also have the responsibility of managing POAPs for the weekly guild calls, it would be extremely valuable to have a new permission available to allow a Level 1 member to access the poap functionality of DEGEN. Currently, this is the case with the analytics guild. A level 1 member was elected to the position while they grow their skills and earn their level 2, with part of their job being to manage poap distribution.

>An example of something similar would be the Guest Pass. The one of the level 2 in the guild involved with the election could assign the guild's poap manager the (revokable) role using DEGEN that will enable the level 1 member to have access to poap control. This should be a timed role, similar to a guest pass, such that it expires after 12 weeks, or whatever the current duration of a season is. 

---
Requestor: zrowgz
Scope of Implementation: analytics guild needed ASAP, but could apply DAO wide
Priority: 5/5 for analytics guild, 3/5 for dao wide implementation
Date needed: Prior to Wednesday October 6th Weekly meeting for the Analytics Guild

**Comment by amaredeus** [comment]
New Authorized degens role is implemented!
