### ISSUE TITLE
SCOAP Squad Overhaul

### ISSUE THREAD

**Issue by wpmonty** [degen-workgroup/DEGEN#242]
Though using the flow and discussing with @tikisailor, I am recommending the following changes be made.

Before doing so, be advised that the original spec and the product Tiki made were the best possible outcome of a Discord-native flow. The cumbersome nature of the current product is not a reflection of the developer's ability, but of the limitations of Discord for this particular product.

*A novel front-end would serve scope squad & role creation much better, but is not an immediate requirement.*

### Recommendations

**Rebrand to "Squad"**

First and foremost - especially for an external facing product/feature - no one knows what SCOAP means. It does not stand for anything and is immediately confusing to users. The feature name should be clear as to not be a barrier to use.

In the recommendations that follow, this rebranding will make additional sense. In essence: rebranding to "Squad" or similar simplifies, clarifies, and makes the feature *flexible* beyond that of scoping.

**Remove Roles**

As mentioned above, the flow is long, cumbersome, and prone for burnout. If we were to pursue a novel frontend with classic CRUD management this would be resolved, but given the current state of use and the fact that a FE can be easily added in later, I recommend to remove roles entirely for now. *Roles are a good idea, but not as a bot dm.*

The result leaves us with a simple "raise your hand" feature.

**Multi Channel**

Posting only to the SCOAP-Squad channel is limiting - unless you are looking only in that channel, it will never reach you. 

In an ideal world, the post could be published to multiple channels - even if just a link to the original message. 

The first version of this could be simply to note an additional second channel (since we do not have a multi-select available, and replicating it would be a bad UX). In a future FE, multi-select will be much more feasible.

Question: Do we still want this to always publish to a "scope-squad" channel? It may not always be relevant.

**Maybe: Waitlist**

In lieu of establishing a number of roles and seats, we could support emoji-select to cap the squad. Any hand-raises after the limit has been reached would be pushed down into a waitlist. This affirms first-come-first-served, but adds additional steps to the process.

**Sucks, but nothing we can do**

Limitations to special characters is a real bummer in writing title and description. FE may solve this, but perhaps we can add a line in the flow to say "special characters are very limited due to Discord rules".

I found myself re-writing my description about 10 times due to small catches/

*Maybe we can callout specific validation errors to address this*

**No Changes**
- Title
- Description

**Comment by amaredeus** [comment]
More details can be found in Mad Hatter!
