### ISSUE TITLE
2FA Prompt

### ISSUE THREAD

**Issue by amaredeus** [degen-workgroup/DEGEN#89]
One of the DAOs contributors had their discord account banned. 

Not exactly sure the reason why but discord does this if they find that the discord account participated in a spam campaign. Because of automated systems this can happen without the user realizing it happened (message sent is quickly deleted). 

It is very very important for everyone to enable 2FA. At minimum lvl2 contributors should do that. 

Can the bot send out a message during the welcome Matt to remind users to enable 2FA?

One step further, can we require 2FA to all lvl 2 contributors? Might be worth discussing with dev guild

**Comment by nonsensecodes** [comment]
This is a great idea. I'm all for tighter security. I think we can regularly pull data from the API to determine who has a Level 2 tag and doesn't have 2FA enabled. If so, we can have DEGEN scrub the list once a week and DM those who haven't enabled it do so. This would fall under the job scheduler feature, methinks.

**Comment by amaredeus** [comment]
Great work everyone on the research!
